# Window configuration (changes require restart).
window:
  dimensions:
    columns: 120
    lines: 30
  decorations: None

background_opacity: 0.95

# Font configuration (changes require restart).
font:
  size: 14
  normal:
    family: CodeNewRoman Nerd Font Mono
    style: Regular

  bold:
    family: CodeNewRoman Nerd Font Mono
    style: Semibold

  italic:
    family: CodeNewRoman Nerd Font Mono
    style: Italic

  offset:
    x: 0
    y: 6

# Color configuration.
# https://github.com/alacritty/alacritty/wiki/Color-schemes
# VSCode's integrated terminal default colors
# Primary and dimmed colors needed
colors:
  # Default colors
  primary:
    background: '#1e1e1e' #Background from Dark Theme

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#cd3131'
    green:   '#0dbc79'
    yellow:  '#e5e510'
    blue:    '#2472c8'
    magenta: '#bc3fbc'
    cyan:    '#11a8cd'
    white:   '#e5e5e5'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#f14c4c'
    green:   '#23d18b'
    yellow:  '#f5f543'
    blue:    '#3b8eea'
    magenta: '#d670d6'
    cyan:    '#29b8db'
    white:   '#e5e5e5'
