# Window configuration (changes require restart).
window:
  dimensions:
    columns: 120
    lines: 30
  decorations: None

background_opacity: 0.95

# Font configuration (changes require restart).
# backup font: "CodeNewRoman Nerd Font Mono" with offset y:3
font:
  size: 13
  normal:
    family: Jetbrains Mono
    style: Regular

  bold:
    family: Jetbrains Mono
    style: Bold

  italic:
    family: Jetbrains Mono
    style: Italic

  offset:
    x: 0
    y: 0

# Color configuration.
# https://github.com/eendroroy/alacritty-theme
# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: '0x0A0E14'
    foreground: '0xFFFFFF'

  # Normal colors
  normal:
    black:   '0x01060E'
    red:     '0xEA6C73'
    green:   '0x91B362'
    yellow:  '0xF9AF4F'
    blue:    '0x53BDFA'
    magenta: '0xFAE994'
    cyan:    '0x90E1C6'
    white:   '0xC7C7C7'

  # Bright colors
  bright:
    black:   '0x686868'
    red:     '0xF07178'
    green:   '0xC2D94C'
    yellow:  '0xFFB454'
    blue:    '0x59C2FF'
    magenta: '0xFFEE99'
    cyan:    '0x95E6CB'
    white:   '0xFFFFFF'
