# Window configuration (changes require restart).
window:
  dimensions:
    columns: 120
    lines: 30
  decorations: full
  gtk_theme_variant: dark

background_opacity: 0.98

# Font configuration (changes require restart).
font:
  size: 15
  normal:
    family: CodeNewRoman Nerd Font Mono
    style: Regular

  bold:
    family: CodeNewRoman Nerd Font Mono
    style: Bold

  italic:
    family: CodeNewRoman Nerd Font Mono
    style: Italic

  offset:
    x: 0
    y: 3

# Color configuration.
# https://github.com/alacritty/alacritty/wiki/Color-schemes
# Colors (Night Owl)
colors:
   # Default colors
  primary:
    # background: '#011627'
    background: '#111213'
    foreground: '#d6deeb'

  cursor:
    text: '#011627'
    cursor: '#d6deeb'

  selection:
    background: '#1b90dd'

   # Normal colors
  normal:
    black:   '#011627'
    red:     '#ef5350'
    green:   '#22da6e'
    yellow:  '#c5e478'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#21c7a8'
    white:   '#ffffff'

   # Bright colors
  bright:
    black:   '#575656'
    red:     '#ef5350'
    green:   '#22da6e'
    yellow:  '#ffeb95'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#7fdbca'
    white:   '#ffffff'
