# Env variables.
env:
  # https://github.com/alacritty/alacritty/issues/3424#issue-576635376
  WINIT_X11_SCALE_FACTOR: "1"

# Window configuration (changes require restart).
window:
  dimensions:
    columns: 120
    lines: 30
  decorations: none
  padding:
    x: 0
    y: 0

background_opacity: 0.98

# Font configuration (changes require restart).
# Alternative font: CodeNewRoman Nerd Font Mono
font:
  size: 13
  normal:
    family: Source Code Pro
    style: Medium

  bold:
    family: Source Code Pro
    style: Bold

  italic:
    family: Source Code Pro
    style: Italic

  offset:
    x: 0
    y: 0

# Color configuration.
# https://github.com/alacritty/alacritty/wiki/Color-schemes
# Colors (Night Owl)
colors:
   # Default colors
  primary:
    # background: '#011627'
    background: '#111213'
    foreground: '#d6deeb'

  cursor:
    text: '#011627'
    cursor: '#d6deeb'

  selection:
    background: '#1b90dd'

   # Normal colors
  normal:
    black:   '#011627'
    red:     '#ef5350'
    green:   '#22da6e'
    yellow:  '#c5e478'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#21c7a8'
    white:   '#ffffff'

   # Bright colors
  bright:
    black:   '#575656'
    red:     '#ef5350'
    green:   '#22da6e'
    yellow:  '#ffeb95'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#7fdbca'
    white:   '#ffffff'
