# Zsh.
# https://github.com/romkatv/powerlevel10k/issues/1474#issuecomment-875062137
export ZLE_RPROMPT_INDENT=0

# Tmux.
export TMUX_PLUGIN_MANAGER_PATH="$HOME"/.config/tmux/plugins/

# Qt.
export QT_QPA_PLATFORM=xcb
export QT_QPA_PLATFORMTHEME=qt5ct

# GUI
# https://github.com/alacritty/alacritty/issues/3299#issuecomment-582789847
export WINIT_UNIX_BACKEND=x11
export WINIT_X11_SCALE_FACTOR=1
export XDG_SESSION_TYPE=x11

# Python.
# https://github.com/python-poetry/poetry/issues/5250#issuecomment-1067193647
export PYTHON_KEYRING_BACKEND=keyring.backends.fail.Keyring

# Golang.
export GOPATH="$HOME/.local/share/go"
export GOMODCACHE="$HOME/.local/share/go/pkg/mod"

# Python.
# https://www.andreagrandi.it/2018/10/16/using-ipdb-with-python-37-breakpoint/
export PYTHONBREAKPOINT=ipdb.set_trace

# https://stackoverflow.com/a/22481496
export TERM="xterm-256color"

# Editors.
export VISUAL=nvim
export EDITOR=nvim
export TERMINAL=alacritty

# Bat
export BAT_THEME='ansi'

# Fzf.
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS='--no-separator --inline-info --cycle --tabstop=4 --bind alt-up:preview-half-page-up,alt-down:preview-half-page-down --height ~70% --layout=reverse --preview-window=noborder --color "hl+:#EB5E55,gutter:#0f0f0f,pointer:#D81E5B"'

# Ghq.
export GHQ_ROOT="$HOME/Workspaces"

# Most.
export MOST_INITFILE="$HOME"/.config/most/mostrc

# Man
export MANPAGER=most

# Go.
GOPRIVATE="gitlab.ci.fdmg.org/*"

# General.
export PATH="$PATH:$HOME/.local/bin:$GOPATH/bin"
