# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "nvidia"
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidia_drm"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [ "amdgpu.sg_display=0" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ lenovo-legion-module ];

  # Filesystem.
  fileSystems."/" = {
    device = "/dev/mapper/luks-0a089b07-f6e9-4a3f-95c0-e95e7de6944d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0a089b07-f6e9-4a3f-95c0-e95e7de6944d".device =
    "/dev/disk/by-uuid/0a089b07-f6e9-4a3f-95c0-e95e7de6944d";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F16A-0A66";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Swap.
  swapDevices = [
    {
      device = "/swapfile";
      size = 16 * 1024; # 32GB
    }
  ];

  # GPU driver (NVIDIA + AMD hybrid).
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  services.xserver.videoDrivers = lib.mkForce [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true;
    open = true;
    nvidiaSettings = true;
    prime = {
      offload = {
        enable = true;
        enableOffloadCmd = true;
      };
      amdgpuBusId = "PCI:5:0:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
