# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Filesystem.
  fileSystems."/" = {
    device = "/dev/mapper/luks-0a089b07-f6e9-4a3f-95c0-e95e7de6944d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0a089b07-f6e9-4a3f-95c0-e95e7de6944d".device =
    "/dev/disk/by-uuid/0a089b07-f6e9-4a3f-95c0-e95e7de6944d";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F16A-0A66";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Swap.
  swapDevices = [
    {
      device = "/swapfile";
      size = 16 * 1024; # 32GB
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
