# colors:  https://github.com/pineapplegiant/spaceduck
format = """
$sudo\
$username\
[](bg:#30365F fg:#00a3cc)\
$directory\
[](fg:#30365F bg:#686f9a)\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#686f9a bg:#393D56)\
$status\
[](fg:#393D56) """

right_format = """
$python\
$container\
$kubernetes\
$helm\
$aws\
$terraform\
$env_var\
$cmd_duration\
$jobs\
"""

continuation_prompt = '>>'
add_newline = false

[username]
show_always = true
style_user = 'bg:#00a3cc fg:#ecf0c1'
style_root = 'bg:#00a3cc fg:#ecf0c1'
format = '[ $user ]($style)'

[character]
success_symbol = '[>](green)'
error_symbol = '[>](red)'

[directory]
style = 'bg:#30365F fg:#ecf0c1'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[git_status]
deleted = 'x'
renamed = '>>'
staged = '+'
modified = '!'
untracked = '?'
conflicted = '='
ahead = ''
behind = ''
diverged = ''
style = 'bg:#686f9a fg:#ecf0c1'
format = '[[($all_status$ahead_behind)]($style)]($style)'

[git_branch]
symbol = ''
style = 'bg:#686f9a fg:#ecf0c1'
format = '[[ $symbol $branch ]($style)]($style)'

[git_commit]
tag_disabled = false
tag_symbol = ' 笠'
style = 'bg:#686f9a fg:#5ccc96'
format = '[\($hash$tag\) ]($style)($style)'

[git_state]
style = 'bg:#686f9a fg:#ecf0c1'
format = '[\([$state( $progress_current/$progress_total)\) ]($style)]($style)'

[status]
style = 'bold bg:#393D56 fg:#ce6f8f'
format = '[ $status ]($style)'
disabled = false

[python]
style = 'fg:#e39400'
format = '[\[$virtualenv\]]($style)'

[aws]
style = 'fg:#5ccc96'
format = '[$profile(\[$region\])(\[$duration\])]($style)'

[terraform]
style = 'fg:#5ccc96'
format = '[\[$workspace\]]($style)'
