# colors:
# https://coolors.co/351431-eb5e55-d81e5b-f3a712-f0cea0
# https://github.com/pineapplegiant/spaceduck
format = """
$sudo\
$username\
[](fg:#351431 bg:#EB5E55)\
$directory\
[](fg:#EB5E55 bg:#D81E5B)\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#D81E5B bg:#393D56)\
$status\
[](fg:#393D56) """

right_format = """
$python\
$container\
$kubernetes\
$helm\
$aws\
$terraform\
$env_var\
$cmd_duration\
$jobs"""

continuation_prompt = '>>'
add_newline = false

[username]
show_always = true
style_user = 'bg:#351431 fg:#ecf0c1'
style_root = 'bg:#351431 fg:#ecf0c1'
format = '[ $user ]($style)'

[directory]
style = 'bg:#EB5E55 fg:#ecf0c1'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[git_status]
deleted = 'x'
renamed = '>>'
staged = '+'
modified = '!'
untracked = '?'
conflicted = '='
ahead = ''
behind = ''
diverged = ''
style = 'bg:#D81E5B fg:#ecf0c1'
format = '[[($all_status$ahead_behind)]($style)]($style)'

[git_branch]
symbol = ''
style = 'bg:#D81E5B fg:#ecf0c1'
format = '[[ $symbol $branch ]($style)]($style)'

[git_commit]
tag_disabled = false
tag_symbol = ' 笠'
style = 'bg:#D81E5B fg:#5ccc96'
format = '[\($hash$tag\) ]($style)($style)'

[git_state]
style = 'bg:#D81E5B fg:#ecf0c1'
format = '[\([$state( $progress_current/$progress_total)\) ]($style)]($style)'

[status]
style = 'bold bg:#393D56 fg:#e39400'
format = '[ $status ]($style)'
disabled = false

[python]
style = 'fg:#e39400'
format = '[\[$virtualenv\]]($style)'

[aws]
style = 'fg:#F0CEA0'
format = '[$profile(\[$region\])(\[$duration\])]($style)'

[terraform]
style = 'fg:#5ccc96'
format = '[\[$workspace\]]($style)'

[cmd_duration]
format = '[$duration]($style)'

[jobs]
symbol = '+'
style = 'bold fg:#D81E5B'
number_threshold = 1
format = '[\[$symbol$number\]]($style)'
