format = """
$sudo\
$username\
[](bg:#DA627D fg:#B93C89)\
$directory\
[](fg:#DA627D bg:#403659)\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#403659) """

right_format = """
$cmake\
$golang\
$helm\
$lua\
$python\
$red\
$rust\
$container\
$docker_context\
$kubernetes\
$terraform\
$vagrant\
$aws\
$gcloud\
$env_var\
$cmd_duration\
$line_break\
$jobs\
$status\
"""

continuation_prompt = ">>"
add_newline = false

[username]
show_always = true
style_user = "bg:#B93C89 fg:#FFFFFF"
style_root = "bg:#B93C89 fg:#FFFFFF"
format = '[ $user ]($style)'

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"

[directory]
style = "bg:#DA627D fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
deleted = "x"
renamed = ">>"
staged = "+"
modified = "!"
untracked = "?"
conflicted = "="
ahead = ""
behind = ""
diverged = ""
style = "bg:#403659 fg:#FFFFFF"
format = '[[($all_status$ahead_behind)](bg:#403659)]($style)'

[git_branch]
symbol = ""
style = "bg:#403659"
format = '[[ $symbol $branch ](bg:#403659)]($style)'

[git_commit]
tag_disabled = false
tag_symbol = " 笠"
style = "bold bg:#403659 fg:#5ccc96"
format = '[\($hash$tag\) ](bold bg:#403659 fg:#5ccc96)($style)'

[git_state]
style = "bold bg:#403659 fg:#e39400"
format = '[\([$state( $progress_current/$progress_total)\) ](bold bg:#403659 fg:#e39400)]($style)'

[python]
symbol = "py:"
style = "yellow"

[golang]
symbol = "go:"
style = "yellow"
