# colors:
# https://coolors.co/1f2041-4b3f72-ffc857-119da4-19647e
# https://github.com/pineapplegiant/spaceduck
format = """
$sudo\
$username\
(fg:#1F2041 bg:#4B3F72)\
$directory\
(fg:#4B3F72 bg:#119DA4)\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status \
$fill \
$status\
$container\
$kubernetes\
$helm\
$terraform\
$env_var\
$cmd_duration\
$jobs\n$character\
"""

continuation_prompt = '>>'
add_newline = false

[fill]
symbol = '-'
style = 'fg:#30365F'

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[username]
show_always = true
style_user = 'bg:#1F2041 fg:#EED3EB'
style_root = 'bg:#1F2041 fg:#EED3EB'
format = '[ $user ]($style)'

[directory]
style = 'bg:#4B3F72 fg:#ecf0c1'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[git_status]
style = 'bg:#119DA4 fg:#ecf0c1'
format = '[$all_status$ahead_behind ]($style)'

[git_branch]
style = 'bg:#119DA4 fg:#ecf0c1'
format = '[ $symbol $branch ]($style)'

[git_commit]
tag_disabled = false
tag_symbol = ' 笠'
style = 'bg:#119DA4 fg:#ecf0c1'
format = '[\($hash$tag\) ]($style)'

[git_state]
style = 'bg:#119DA4 fg:#ecf0c1'
format = '[\($state( $progress_current/$progress_total)\) ]($style)'

[status]
style = 'bold bg:#119DA4 fg:#ecf0c1'
format = '[ $status ]($style)'
disabled = false

[aws]
style = 'fg:#F0CEA0'
format = '[$profile(\[$region\])(\[$duration\])]($style)'

[terraform]
style = 'fg:#5ccc96'
format = '[\[$workspace\]]($style)'

[cmd_duration]
format = '[$duration]($style)'

[jobs]
symbol = '+'
style = 'bold fg:#19647E'
number_threshold = 1
format = '[\[$symbol$number\]]($style)'
