# colors:  https://github.com/pineapplegiant/spaceduck
format = """
$sudo\
$username\
[](bg:#30365F fg:#ce6f8f)\
$directory\
[](fg:#30365F bg:#686f9a)\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#686f9a) """

right_format = """
$cmake\
$golang\
$helm\
$lua\
$python\
$red\
$rust\
$container\
$docker_context\
$kubernetes\
$terraform\
$vagrant\
$aws\
$gcloud\
$env_var\
$cmd_duration\
$status\
"""

continuation_prompt = ">>"
add_newline = false

[username]
show_always = true
style_user = "bg:#ce6f8f fg:#ecf0c1"
style_root = "bg:#ce6f8f fg:#ecf0c1"
format = '[ $user ]($style)'

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"

[directory]
style = "bg:#30365F fg:#ecf0c1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_status]
deleted = "x"
renamed = ">>"
staged = "+"
modified = "!"
untracked = "?"
conflicted = "="
ahead = ""
behind = ""
diverged = ""
style = "bg:#686f9a fg:#ecf0c1"
format = '[[($all_status$ahead_behind)]($style)]($style)'

[git_branch]
symbol = ""
style = "bg:#686f9a fg:#ecf0c1"
format = '[[ $symbol $branch ]($style)]($style)'

[git_commit]
tag_disabled = false
tag_symbol = " 笠"
style = "bold bg:#526CA3 fg:#5ccc96"
format = '[\($hash$tag\) ]($style)($style)'

[git_state]
style = "bold bg:#7a5ccc fg:#ecf0c1"
format = '[\([$state( $progress_current/$progress_total)\) ]($style)]($style)'

[python]
symbol = "py:"
style = "yellow"

[golang]
symbol = "go:"
style = "yellow"

