# colors:
# https://coolors.co/351431-eb5e55-e23e58-d81e5b-f3a712-f8eedf
# https://coolors.co/1f2041-4b3f72-ffc857-119da4-19647e
# https://github.com/pineapplegiant/spaceduck
format = """
$sudo\
$username\
[](bg:#212529 fg:#023e8a)\
$directory\
[](fg:#212529 bg:#343a40)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#343a40) """

right_format = """
$status\
$container\
$kubernetes\
$helm\
$terraform\
$env_var\
$cmd_duration\
$jobs"""

continuation_prompt = '>>'
add_newline = false

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[username]
show_always = true
style_user = 'bg:#023e8a fg:#F8EEDF'
style_root = 'bg:#023e8a fg:#F8EEDF'
format = '[ $user ]($style)'

[directory]
style = 'bg:#212529 fg:#F8EEDF'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
symbol = ''
style = 'bg:#343a40 fg:#F8EEDF'
format = '[ $symbol$branch]($style)'

[git_commit]
tag_disabled = false
style = 'bg:#343a40 fg:#F8EEDF'
format = '[\($hash$tag\)]($style)'

[git_state]
style = 'bg:#343a40 fg:#F8EEDF'
format = '[\($state($progress_current/$progress_total)\)]($style)'

[git_status]
ahead = '󰁝'
behind = '󰁅'
diverged = '󰹹'
deleted = 'x'
style = 'bg:#343a40 fg:#F8EEDF'
format = '[$all_status$ahead_behind ]($style)'

[status]
style = 'bold bg:#D12E4F fg:#F8EEDF'
format = '[ $status ]($style)'
disabled = false

[aws]
style = 'fg:#F0CEA0'
format = '[$profile(\[$region\])(\[$duration\])]($style)'

[terraform]
style = 'fg:#5ccc96'
format = '[\[$workspace\]]($style)'

[cmd_duration]
format = '[$duration]($style)'

[jobs]
symbol = '+'
style = 'bold fg:#19647E'
number_threshold = 1
format = '[\[$symbol$number\]]($style)'
