# colors:
# https://coolors.co/351431-eb5e55-e23e58-d81e5b-f3a712-f0cea0
# https://github.com/pineapplegiant/spaceduck
format = """
$sudo\
$username\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#E23E58) """

right_format = """
$status\
$container\
$kubernetes\
$helm\
$terraform\
$env_var\
$cmd_duration\
$jobs"""

continuation_prompt = '>>'
add_newline = false

[username]
show_always = true
style_user = 'bg:#351431 fg:#EED3EB'
style_root = 'bg:#351431 fg:#EED3EB'
format = '[ $user ]($style)'

[directory]
style = 'bg:#E23E58 fg:#ecf0c1'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[git_status]
deleted = 'x'
renamed = '>>'
staged = '+'
modified = '!'
untracked = '?'
conflicted = '='
ahead = ''
behind = ''
diverged = ''
style = 'bg:#D81E5B fg:#ecf0c1'
format = '[$all_status$ahead_behind ]($style)'

[git_branch]
symbol = ''
style = 'bg:#D81E5B fg:#ecf0c1'
format = '[ $symbol $branch ]($style)'

[git_commit]
tag_disabled = false
tag_symbol = ' 笠'
style = 'bg:#D81E5B fg:#ecf0c1'
format = '[\($hash$tag\) ]($style)'

[git_state]
style = 'bg:#D81E5B fg:#ecf0c1'
format = '[\($state( $progress_current/$progress_total)\) ]($style)'

[status]
style = 'bold bg:#D81E5B fg:#ecf0c1'
format = '[ $status ]($style)'
disabled = false

[aws]
style = 'fg:#F0CEA0'
format = '[$profile(\[$region\])(\[$duration\])]($style)'

[terraform]
style = 'fg:#5ccc96'
format = '[\[$workspace\]]($style)'

[cmd_duration]
format = '[$duration]($style)'

[jobs]
symbol = '+'
style = 'bold fg:#D81E5B'
number_threshold = 1
format = '[\[$symbol$number\]]($style)'
