#! /bin/sh
# colors: https://github.com/pineapplegiant/spaceduck

# Monitor.
bspc config merge_overlapping_monitors false

# Keybinding.
pgrep -x sxhkd > /dev/null || sxhkd &

# Mouse.
xsetroot -cursor_name arrow

# Bluetooth.
blueman-applet &

# Status bar.
nm-applet &
polybar main --log=error &

# Lock screen.
xset s 180
xss-lock --transfer-sleep-lock -- xsecurelock &

# Background.
hsetroot -solid '#0f0f0f'

# Screenshot.
flameshot &

# Clipboard.
greenclip daemon>/dev/null &

# Mount.
udiskie &

# Bspwm.
bspc monitor -d 0 1 2 3 4

bspc config border_width          1
bspc config focused_border_color  \#9A83D8
bspc config normal_border_color   \#686f9a
bspc config active_border_color   \#686f9a
bspc config presel_feedback_color \#686f9a

bspc config window_gap           5
bspc config top_padding          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false

# Application rules.
bspc rule -a firefox desktop=0
bspc rule -a Microsoft\ Teams\ -\ Preview:\* desktop=0
bspc rule -a Microsoft\ Teams\ -\ Preview:\* split_ratio 0.61
