#! /bin/sh

# Keybinding.
pgrep -x sxhkd > /dev/null || sxhkd &

# Default resolution (laptop).
xrandr --output eDP-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off

# Status bar.
nm-applet &
polybar &

# Lock screen.
xset s 180
xss-lock --transfer-sleep-lock -- xsecurelock &

# Background.
feh --bg-scale "$HOME/.config/bspwm/wallpaper.jpg" &

# Screenshot.
flameshot &

# Clipboard.
greenclip daemon>/dev/null &

# Mount.
udiskie &

# Bspwm.
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
# colors: https://github.com/pineapplegiant/spaceduck
bspc config focused_border_color \#7a5ccc
bspc config normal_border_color  \#686f9a
bspc config active_border_color  \#686f9a

bspc config window_gap           10

bspc config top_padding          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Application rules.
bspc rule -a firefox desktop=^1
