[theme]
name = "dracula"
[theme.overrides]
separator = ""

[icons]
name = "none"

[[block]]
block = "docker"
interval = 2
format = "{running} {total} {images}"
[block.theme_overrides]
idle_fg = "#b3a1e6"
good_fg = "#b3a1e6"
[block.icons_overrides]
docker = ""

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "notify"
format = ""

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
[block.icons_overrides]
time = ""

[[block]]
block = "custom"
command = '''echo $(curl -s http://ip-api.com/json | jq -r ".countryCode")'''
interval = 30
[block.theme_overrides]
idle_fg = "#5ccc96"
good_fg = "#5ccc96"

[[block]]
block = "custom"
command = '''echo $(torify curl -s http://ip-api.com/json | jq -r ".countryCode")'''
interval = 30
[block.theme_overrides]
idle_fg = "#f2ce00"
good_fg = "#f2ce00"
