[theme]
name = "dracula"
[theme.overrides]
separator = " "

[icons]
name = "none"

[[block]]
block = "docker"
interval = 2
format = "{running} {total} {images}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "notify"
format = ""

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "custom"
command = "echo "
on_click = "flameshot gui"

[[block]]
block = "custom"
command = "echo "
on_click = "zeal"

[[block]]
block = "custom"
command = "echo "
on_click = "shutdown now"


