# ayu-dark + customized colors
# https://github.com/alacritty/alacritty-theme/blob/master/themes/ayu_dark.toml

# Default colors
[colors.primary]
background = '#0B1015'
foreground = '#F5E2C8'

[colors.cursor]
cursor = '#c0caf5'
text   = '#1a1b26'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#AF52FA'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#AF52FA'
cyan    = '#95E6CB'
white   = '#FFFFFF'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[cursor.style]
blinking = "Always"

[cursor.vi_mode_style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
style = "Medium"

[font.offset]
x = 0
y = -1

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
opacity         = 1.0
dynamic_title   = false

[window.dimensions]
columns = 200
lines   = 40

[window.padding]
x = 10
y = 10
